DROP TABLE IF EXISTS RES_RISK_SCORE;
CREATE TABLE RES_RISK_SCORE(
   RES_ENT_ID BIGINT,
   LENS_ID SMALLINT,
   QUALITY_STATE VARCHAR(10),
   COLLISION_STATE VARCHAR(10),
   QUERY_STATE VARCHAR(10),
   REASON VARCHAR(500),
   QUERY_REASON VARCHAR(200),
   PRIMARY KEY(RES_ENT_ID, LENS_ID)
);
CREATE INDEX RES_RISK_SCORE_QS ON RES_RISK_SCORE(QUALITY_STATE);
CREATE INDEX RES_RISK_SCORE_CS ON RES_RISK_SCORE(COLLISION_STATE);
CREATE INDEX RES_RISK_SCORE_QS2 ON RES_RISK_SCORE(QUERY_STATE);
